### ISSUE TITLE
Better search - split words also on brackets

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/osmfeatures#11]
"Alcohol shop" and "Alcohol" should be able to find "Off licence (Alcohol shop)" entry

See see https://github.com/streetcomplete/StreetComplete/issues/3894

**Comment by westnordost** [comment]
Related code:

https://github.com/westnordost/osmfeatures/blob/master/library/src/main/java/de/westnordost/osmfeatures/FeatureDictionary.java#L321-L329

Feature dictionary does not recognize "(" (and everything else except whitespace) as a separator of a word. So, it looks like the splitting of words in a string could be smarter.

A PR is welcome if tests are added for the modified behavior.

**Comment by Cj-Malone** [comment]
Is this as simple as adding `.replace("(", "").replace(")", "");` to the end of line 322, or am I under thinking it?

**Comment by westnordost** [comment]
Try it out. I propose you write a test first of the result you would like to see, then do the changes in the code that hopefully get to that result. Maybe there are other characters too that should be taken into account.

**Comment by westnordost** [comment]
Noone wants to do this? It should not be too much work, I've given the location in the source where it can be fixed and the osmfeatures project is really small in size.

**Comment by Cj-Malone** [comment]
I'd need some help writing the tests, but I'd like to try. PS not a developer.

Last night I managed to get Gradle to build the library without the Android stuff, I had to move the `library` directory out of `osmfeatures` because `library-android` kept getting pulled in.

**Comment by westnordost** [comment]
library-android depends on library. You don't need to build library-android if you just change things on the library.

This is the easiest (IMO) way to run the tests
![image](https://user-images.githubusercontent.com/4661658/160209484-2f2a69cb-8367-4e84-9ae6-3fa54fc72d54.png)
alternatively
![image](https://user-images.githubusercontent.com/4661658/160209598-54101c53-ace9-4fa5-8ef6-40974a3ca72e.png)
(it may actually do the exact same thing)

**Comment by westnordost** [comment]
Alternatively, run `gradlew test` in the directory in any terminal (such as the one integrated in Android Studio)

![image](https://user-images.githubusercontent.com/4661658/160209898-07063c33-417a-4610-ac61-9509e1cd7013.png)

**Comment by Cj-Malone** [comment]
I'm not using Android Studio, or have the Android SDK installed. Running `gradle :library:test` in `osmfeatures` or `gradle test` in `library` both try and pull in `library-android/build.gradle` requiring the Android SDK.

Anyway, Gradle aside, I opened #12, no tests yet.
