### ISSUE TITLE
"Alcohol shop" should be able to find "Liquor store" entry

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/osmfeatures#13]
rerun of https://github.com/streetcomplete/StreetComplete/issues/3894

"Alcohol" now finds this entry but "Alcohol shop" does not. It is not critical issue here (prefix is found), but worth investigating in general

**Comment by matkoniecz** [comment]
It is actually different aspect of https://github.com/openstreetmap/id-tagging-schema/issues/461 and one of solutions is to improve aliases provided by iD presets.

**Comment by westnordost** [comment]
Can you elaborate?

**Comment by westnordost** [comment]
I see, so this is actually not an issue. Any decision to (also) fall back to another locale should be a client-side decision and not be baked into the distributed translations. In fact, users of this library **can** just fall back to another locale (`findIt ?: findItInDifferentLocale`)

**Comment by matkoniecz** [comment]
There are two pars here:

"Alcohol shop" is unable to find "Off license (Alcohol shop)" in StreetComplete, despite that name matches well (en-UK).

In addition neither StreetComplete not iD can match "Alcohol shop" to "Liquor store" (en-US).

**Comment by westnordost** [comment]
> "Alcohol shop" is unable to find "Off license (Alcohol shop)" in StreetComplete, despite that name matches well (en-UK).

You mean if you type exactly that? And if you just type "off license"?  and if you just type "alcohop shop"?

> In addition neither StreetComplete not iD can match "Alcohol shop" to "Liquor store" (en-US).

That's expected, because it does not turn up in the en-US localization.

**Comment by matkoniecz** [comment]
> You mean if you type exactly that? 

yes

> And if you just type "off license"? 

found

> and if you just type "alcohop shop"?

not found

`alcohol shop` also fails to find it

> That's expected, because it does not turn up in the en-US localization.

And I am proposing to change this in https://github.com/openstreetmap/id-tagging-schema/issues/461

**Comment by westnordost** [comment]
> alcohol shop also finds to find it

Alcohol shop "finds to find it"?

**Comment by matkoniecz** [comment]
`alcohol shop` also fails to find it

**Comment by westnordost** [comment]
So that in Locale en-GB, typing "Alcohol Shop" does not find `shop=alcohol` even though these two words are in the preset name, is a bug then.

**Comment by westnordost** [comment]
Okay, the reason why it is not found is because the preset name is "Off license (alcohol shop)".

If you typed either of the below, it would be found:
- off
- license
- alcohol
- shop
- Off licence 
- Off licence (alco
- Off licence (alcohol shop)

I.e. matching only happens per-word or per-whole-string and each from the start. E.g. "cohol" doesn't match with "alcohol" but "alc" does.

Since "alcohol shop" is really shoehorned into the primary name here, and actually one should be an `alias` of the other, I don't think it is necessary to change anything here.
