### ISSUE TITLE
upcoming schema change in id-tagging-schema repository

### ISSUE THREAD

**Issue by tyrasd** [westnordost/osmfeatures#15]
I have just published a new version of the json schema which is to be used by the upcoming release of iD's tagging presets. See https://github.com/ideditor/schema-builder/blob/main/CHANGELOG.md#510 and https://github.com/openstreetmap/id-tagging-schema/pull/598.

There are two changes I would consider breaking:

* There is a new `colour` field type, which should be pretty self-explanatory and can be handled like a `combo` field if no dedicated color input method is available or needed.
* The schema now allows to cross-reference strings in presets and fields. This is intended used, for example, when there exist regional variants of a preset: By cross-referencing the name of the original preset, translators don't need to re-translate the same preset over and over again. Strings that are cross-referenced are missing in the `dist/translations` data, and are instead included in the `presets[.min].json` (or `fields[.min].json`) and use the same curly-bracket syntax that is used to cross-reference fields of preset (e.g. `"label": "{building/levels}"` in the `building/levels_building` field means that the field should use the same label as the `building/levels` field). The following strings can be cross-referenced:
  * a preset's `name` (if used, this implies that `aliases` and `terms` should also be used from the other preset)
  * a field's `label` (if used, this implies that the `terms` should also be used from the other field)
  * a field's `placeholder`
  * a field's `strings` (which used a dedicated property `stringsCrossReference` in order to keep the schema change to a minimum)

Examples:

field `building/levels_building.json`
```json
{
    "key": "building:levels",
    "type": "number",
    "minValue": 0,
    "label": "{building/levels}",
    "placeholder": "{building/levels}",
    "prerequisiteTag": {
        "key": "building",
        "valueNot": "no"
    }
}
```

field `payment_multi_fee.json`
```
{
    "key": "payment:",
    "type": "multiCombo",
    "label": "{payment_multi}",
    "prerequisiteTag": {
        "key": "fee",
        "valueNot": "no"
    },
    "options": […],
    "stringsCrossReference": "{payment_multi}"
}
```

preset `highway/motorway_link-US-CA.json`
```json
{
    "name": "{highway/motorway_link}",
    "icon": "iD-highway-motorway-link",
    "fields": […],
    "moreFields": […],
    "geometry": [
        "line"
    ],
    "tags": {
        "highway": "motorway_link"
    },
    "locationSet": {
        "include": [
            "ca",
            "us"
        ]
    }
}
```

This change will likely already affect the next version of released iD presets in a couple of weeks.

PS: I just noticed that in the usage instructions, you're using a non-versioned URL to the presets data. This might not be recommendable, as the schema can always include breaking changes on major version upgrades.

**Comment by westnordost** [comment]
Thanks for the notice!
