### ISSUE TITLE
Being able to find country-specific features

### ISSUE THREAD

**Issue by westnordost** [westnordost/osmfeatures#23]
Currently, all (non-brand) features indexed globally. IIRC, thus, features that *are* country-specific can thus not be found by this library.

See https://github.com/streetcomplete/StreetComplete/issues/4916

**Comment by valerio-bozzolan** [comment]
Trying to understand the next actionable thing but it seems `dictionary.getByTerm()` already supports a filter by `country` :exploding_head:

https://github.com/westnordost/osmfeatures/blob/11a1c94cd5dbd3ff9f6bc0885fdcaa865a1e70a8/src/commonMain/kotlin/de/westnordost/osmfeatures/FeatureDictionary.kt#L192

https://github.com/westnordost/osmfeatures/blob/11a1c94cd5dbd3ff9f6bc0885fdcaa865a1e70a8/src/commonMain/kotlin/de/westnordost/osmfeatures/FeatureDictionary.kt#L432

https://github.com/westnordost/osmfeatures/blob/11a1c94cd5dbd3ff9f6bc0885fdcaa865a1e70a8/src/commonMain/kotlin/de/westnordost/osmfeatures/FeatureDictionary.kt#L432

**Comment by mnalis** [comment]
> Trying to understand the next actionable thing but it seems `dictionary.getByTerm()` already supports a filter by country 🤯

Interesting, but does it work though? 

Because StreetComplete seems to be sending that `countryOrSubdivisionCode` param in [Things overlay](https://github.com/streetcomplete/StreetComplete/blob/v59.1/app/src/main/java/de/westnordost/streetcomplete/overlays/things/ThingsOverlayForm.kt#L78-L83), but the "Mail Drop Box" (`amenity=post_box`) doesn't show in search results (https://github.com/streetcomplete/StreetComplete/issues/4916). 

So either `countryOrSubdivisionCode` in StreetComplete is `null`, or `getByTerm()` here doesn't work as advertised. It would need to be debugged.

**Comment by westnordost** [comment]
Nothing on the API would need to be changed to accommodate this feature, correct.

The postbox feature is also in the dictionary. It is just not indexed (and the search uses exclusively the indices to search)

**Comment by mnalis** [comment]
What I find interesting that while searching for postbox also fails in SCEE Things Overlay, SCEE also has [long-press-to-Add-POI](https://github.com/Helium314/SCEE/blob/76df3dbb281984d9b5d030cfab0cfc8606df9fd1/app/src/main/java/de/westnordost/streetcomplete/screens/main/MainFragment.kt#L1263-L1280) feature,  and that one **manages to find _"Mail Drop Box"_ (`amenity=post_box`) just fine!**

However, tracking what it does differently is beyond my capabilities; but there seems to be some way (perhaps not using indexes, but I do not notice that search is _any_ slower -- it is relatively recent phone [Samsung Galaxy S23+] though, so it may be it is just too fast to notice)?

![small_Screenshot_20241003_170720_SCEE](https://github.com/user-attachments/assets/05f0959b-6894-4d67-be19-4c6e14efc6c8) ![small_Screenshot_20241003_170748_SCEE](https://github.com/user-attachments/assets/7e36e546-8975-4ec0-8a3c-8cfdfe72ba15)

**Comment by westnordost** [comment]
Actually, it **is** indexed. I was wrong about the source of streetcomplete#5945 all along!

Also, it looks like finding country-specific features also is already working, all along! There was a small bug, but it should actually not matter. 

So, I am now investigating where the real culprit lies.

**Comment by westnordost** [comment]
closing as invalid
