### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by westnordost** [westnordost/osmfeatures#3]
I noticed the name "osmnames" is already taken:
https://duckduckgo.com/?q=osmnames&ia=software

So maybe I should rename this. It should be short, but also descriptive of what it does:
_A dictionary of [map features](https://wiki.openstreetmap.org/wiki/Map_Features), accessible by terms and by tags._

So, maybe:
- osm-map-features
- map-features
- map-features-dictionary

**Comment by exploide** [comment]
- osm-feature-dict

or perhaps more general and shorter:
- osm-dict

**Comment by westnordost** [comment]
Also good idea, though, it is also possible to have a dictionary of OSM keys and OSM values (not map features). For example:

Key: surface -> Oberfläche 
Tag: surface=sett -> Steinpflaster 

etc.
But this library doesn't do that.

Am 16. April 2019 17:52:47 MESZ schrieb Jannik Vieten <notifications@github.com>:
>- osm-feature-dict
>
>or perhaps more general and shorter:
>- osm-dict

**Comment by exploide** [comment]
True. I imagined the lib will do this eventually in the future. :P

**Comment by westnordost** [comment]
Maybe I will do this in the future (data source can be the same), but features <-> presets/fields/tags/keys is a good point to separate.

I will simply use "osmfeatures".
