### ISSUE TITLE
how to get osmfeatures-android 2.0?

### ISSUE THREAD

**Issue by Helium314** [westnordost/osmfeatures#7]
When trying to build StreetComplete 28.0-beta1, I get an error regarding osmfeatures. This seems to be due to 
https://jcenter.bintray.com/de/westnordost/osmfeatures-android/2.0/ giving a not-found message.

Am I doing something wrong here? Since I appear to be the only one having this problem...

(and btw the links in the readme.md don't work, as they don't use https)

**Comment by westnordost** [comment]
Oh, it looks like I forgot to publis this one. It's published now.
